/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonView: typeof import('./src/components/ButtonView.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpDownload: typeof import('~icons/ep/download')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpLink: typeof import('~icons/ep/link')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    IEpOperation: typeof import('~icons/ep/operation')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpUploadFilled: typeof import('~icons/ep/upload-filled')['default']
    LayoutView: typeof import('./src/components/layout/LayoutView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkView: typeof import('./src/components/RouterLinkView.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
